apiVersion: v2
name: jira-mcp-server
description: A Helm chart for JIRA MCP Server
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - jira
  - mcp
  - ai
  - model-context-protocol
home: https://github.com/royashish/jira-mcp-server-standalone
sources:
  - https://github.com/royashish/jira-mcp-server-standalone
maintainers:
  - name: Ashish Roy
    email: royashish@example.com